# This is a basic workflow to help you get started with Actions

name: download

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: 
      - 'README.md'
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  import:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: function1
        uses:  wow-actions/download-upload@v1.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          url: https://aptoslabs.com/
          filename: knowledge
          commit_message: source from web
          
      - name: function2
        uses: carlosperate/download-file-action@v2.0.0
        with:
          file-url: https://github.com/SAStommy/python/tree/main/finalproject
          file-name: project
          location: /ram
          
      - name: download function2 file
        uses: actions/download-artifact@v3.0.2
        with:
          name: project
          
