
name: aptos test and complie

on:
  push:
    branches: [ "main" ]
    tags:
      - README.md
  workflow_dispatch:

jobs:

  all:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: get aptos cli
        uses: pontem-network/get-aptos@v1.0.6
